config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'

  resources :users do
    resources :transactions, only: %i[index new create show edit update destroy]
    resources :goals, only: %i[new create edit update] do
      member do
        put :cancel
      end
    end
  end

  resources :stats, only: %i[index]
  resources :calculators, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  validates :name, :objective, presence: true

  def cancel!
    self.cancelled = true
    self.save
  end

  def achieve!
    self.achieved = true
    self.save
  end

  def check
    self.cancelled || self.achieved
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :type_transaction, :date, :value, :category, presence: true

  # validates :value, numericality: { greater_than_or_equal_to: 0 }

  EXPENSE_CATEGORIES = ["Rent", "Mortgage", "House Bills", "Insurance", "Health", "Groceries", "Fuel", "Interest",
                        "Leisure"]
  INCOME_CATEGORIES = ["Salary", "Dividends", "Other"]
  ALL_CATEGORIES = ["Rent", "Mortgage", "House Bills", "Insurance", "Health", "Groceries", "Fuel", "Interest",
                    "Leisure", "Salary", "Dividends", "Others"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :goals
  has_one_attached :photo

  def fetch_monthly_income
    income = 0
    transactions = self.transactions.where(transactions: { date: Time.now.beginning_of_month..Time.now.end_of_month })
    transactions.each do |transaction|
      if transaction.type_transaction == "Income"
        income += transaction.value
      end
    end
    format("%.2f", income)
  end

  def fetch_monthly_expense
    expense = 0
    transactions = self.transactions.where(transactions: { date: Time.now.beginning_of_month..Time.now.end_of_month })
    transactions.each do |transaction|
      if transaction.type_transaction == "Expense"
        expense += transaction.value
      end
    end
    format("%.2f", expense)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: :calculators
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController

  def index
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user), notice: "Goal creation failed. You must fill all fields"
    end
  end

  def edit
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.current_value = @goal.current_value + params["goal"]["current_value"].to_i
    @goal.save
      if @goal.current_value > @goal.objective
        @goal.achieve!
        redirect_to user_path(current_user), notice: "Congratulations! You've achieved your goal!"
      else
        redirect_to user_path(current_user)
      end
  end

  def cancel
    goal = current_user.goals.last
    goal.cancel!
    redirect_to user_path(current_user), notice: "Goal cancelled!"
  end


  private

  def goal_params
    params.require(:goal).permit(:name, :objective, :current_value, :achieved, :cancelled)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @user = current_user
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transaction = Transaction.new
    if (params[:query].present? && params[:query] == "all") || !params[:query].present?
      @transactions = current_user.transactions
    else
      @transactions = current_user.transactions.where("type_transaction LIKE ?", params[:query].to_s)
    end
  end

  def new
    @transaction = Transaction.new
    @elem = params[:elem]
    session[:passed_variable] = @elem
  end

  def create
    @elem = session[:passed_variable]
    @transaction = Transaction.new
    @transaction.assign_attributes(transaction_params)
    @transaction.user = current_user
    @transaction.save
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.assign_attributes(transaction_params)
    @changed = @transaction.changed?
    @transaction.save
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to user_transactions_path(current_user)
  end

  private

  def transaction_params
    params.require(:transaction).permit(:type_transaction, :date, :value, :category, :tag)
  end
end

app/controllers/users_controller.rb
require "json"
require "open-uri"

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @transaction = Transaction.new
    @goal = Goal.new
    url = "https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=#{ENV['KEY_NEWS']}"
    news_serialized = URI.open(url).read
    @news = JSON.parse(news_serialized)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def extract_values(transactions)
    display_as_currency(transactions.map { |x| x.type_transaction == "Expense" ? x.value * -1 : x.value }.reduce(:+))
  end

  def user_has_photo?(user)
    return cl_image_tag user.photo.key, :width=>100, :gravity=>"faces", crop: :thumb, radius: "max", :aspect_ratio=>"1.0" if user.photo.attached?

    image_tag "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png",
              width: 70, style: "border-radius:100%"
  end

  def navbar_avatar_has_photo?(user)
    if user.photo.attached?
      return cl_image_tag user.photo.key, height: 40, width: 40, crop: :fill, gravity: :face,
                                          class: "dropdown-toggle", id: "navbarDropdown",
                                          data: { bs_toggle: "dropdown" }, 'aria-haspopup': true,
                                          'aria-expanded': false, style: "border-radius:50%"
    end

    image_tag "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png",
              class: "avatar dropdown-toggle", id: "navbarDropdown",
              data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
  end

  def display_as_currency(value)
    number_with_precision(
      value,
      precision: 2,
      separator: ',',
      delimiter: '.'
    )
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/calculators/index.html.erb
<div class="container mt-3 mb-3">
  <div class="row justify-content-around">
    <div class="card p-2 col-5" style="border-radius: 20px; height: fit-content;">
      <form id="compound">
        <h2>Compound Interest Calculator</h2>
        <P style="color:blue;"><strong>Principal Amount:</strong><input type="text" id="getPrincipalValue" name="principal"  placeholder="Principal" class="form-control" ></P>
        <P style="color:blue;"><strong>Anual Interest Rate (%):</strong><input type="text" id="getInterestRate" name="interest"  placeholder="Interest Rate" class="form-control" ></P>
        <P style="color:blue;"><strong>Compound:</strong> <input type="text" id="getTiming" name="timing"  placeholder="number of time paid" class="form-control" ></P>
        <P style="color:blue;"><strong>Time (in years) :</strong><input type="text" id="getYear" name="year"  placeholder="Year" class="form-control" ></P>
        <P>
        <input type="button" value="Calculate" id="" onclick="compoundInterest();" class="btn btn-primary" style="border-radius: 20px;"/></P>
        <p id="outputPrincipal"> </p>
        <p id="outputInterest"> </p>
        <p id="outputYear"> </p>
        <p id="outputtime"> </p>
        <p id="compounded"> </p>
        <p id="summary"></p>
      </form>
    </div>

    <div class="card p-2 col-5" style="border-radius: 20px; height: fit-content;">
      <form id="compound">
        <h2>Simple Interest Calculator</h2>
        <P style="color:blue;"><strong>Principal Amount:</strong><input type="text" id="getPrincipalValueSimple" name="principal"  placeholder="Principal" class="form-control" ></P>
        <P style="color:blue;"><strong>Anual Interest Rate (%):</strong><input type="text" id="getInterestRateSimple" name="interest"  placeholder="Interest Rate" class="form-control" ></P>
        <P style="color:blue;"><strong>Time (in months) :</strong><input type="text" id="getMonthSimple" name="month"  placeholder="Months" class="form-control" ></P>
        <P>
        <input type="button" value="Calculate" id="" onclick="simpleInterest();" class="btn btn-primary" style="border-radius: 20px;"/></P>
        <p id="outputInterestSimple"> </p>
        <p id="summarySimple"></p>
      </form>
    </div>
  </div>
  <div class="d-flex justify-content-around">
    <div>
    </div>
    <div>

    </div>
  </div>
</div>


<script type="text/javascript">
  function compoundInterest() {
    let principal = document.getElementById("getPrincipalValue").value;
    let interest = document.getElementById("getInterestRate").value;
    let timing = document.getElementById("getTiming").value;
    let years = document.getElementById("getYear").value;

    let interest_rate = interest/100
    let resultCompound  = principal * Math.pow(1 + interest_rate/timing, timing*years);


    document.getElementById("outputPrincipal").innerHTML = "Principal is " + principal;
    document.getElementById("outputInterest").innerHTML = "Interest is " + interest + "%";
    document.getElementById("outputYear").innerHTML = "Number of Years:" + years;
    document.getElementById("outputtime").innerHTML = "Number of time interest paid per year: " + timing;
    document.getElementById("compounded").innerHTML = "Interest Plus Principal: " + Math.round(resultCompound * 100)/100;
    document.getElementById("summary").innerHTML = "The total amount accrued, principal plus interest, with compound interest on a principal of " + principal + " at a rate of " + interest + "% per year compounded " + timing + " times per year over " + years + " years is $" + Math.round(resultCompound * 100)/100;
  }

  function simpleInterest() {
    let principal = document.getElementById("getPrincipalValueSimple").value;
    let interest = document.getElementById("getInterestRateSimple").value;
    let months = document.getElementById("getMonthSimple").value;

    let interest_rate = interest/100
    let monthYear = months/12
    let resultSimple  = principal * interest_rate * monthYear

    document.getElementById("outputInterestSimple").innerHTML = "Interest is " + interest + "%";
    document.getElementById("summarySimple").innerHTML = "The simple interest accumulated on a principal of $ " + principal + " at a rate of " + interest + "% per year for " + monthYear + " years (" + months + " months) is $" + Math.round(resultSimple * 100)/100;
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeadSimpleFinanceTracker</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <div class="page-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <main id="main-content">
        <%= yield %>
      </main>
      <%= render 'shared/footer' %>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<main>
  <div class="container-fluid m-0" id="backhome">
    <div class="row justify-content-between">
      <div class="col-12 col-md-6 col-lg-3" style="margin-left: 60px; margin-top: 30px;">
        <h1 style="color: white; font-family: 'Raleway', arial; line-height: 50px; font-size: 56px; font-weight: bold;">Welcome to Dead Simple Finance</h1>
        <h3 style="color: white; font-family: 'Raleway', arial;">Track your finance with our simple app</h3>
        <%= form_tag new_user_registration_path, method: :get, class: "row" do %>
          <%= text_field_tag "email", nil, placeholder: "Please enter your e-mail", class: "form-control" %>
          <%= submit_tag "Sign in now!", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-12 col-md-6 col-lg-6">
        <%# <img src="https://liferay-cdn.estacioprd.net/documents/316123/357473/Secretariado-Executivo.png/35ea5d8b-08d0-7d39-ad7b-4d80816797e7?t=1595639362236" alt=""> %>
        <img src="https://res.cloudinary.com/dmtwwkxzz/image/upload/v1647286457/pv-_1_sc7cbx.png" alt="">
      </div>
    </div>
  </div>
  <section class="mb-5" style="margin-top: -30px;">
    <div class="container">
      <div class="row align-items-center justify-content-between">
          <div class="card-home card col-12 col-md-3 col-lg-3 pt-3 pb-3">
            <img src="https://img.icons8.com/cotton/512/000000/add-dollar--v2.png"/>
            <h4>Track Your Finances!</h4>
            <p>Control your finances every day.</p>
          </div>
          <div class="card-home card col-12 col-md-3 col-lg-3 pt-3 pb-3">
            <img src="https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/512/000000/external-savings-investment-kiranshastry-lineal-kiranshastry.png"/>
            <h4>Increase Your Savings!</h4>
            <p>Controlling your finances helps to save a lot of money.</p>
          </div>
          <div class="card-home card col-12 col-md-3 col-lg-3 pt-3 pb-3">
            <img src="https://img.icons8.com/ios/500/000000/easy.png"/>
            <h4>Easy To Use!</h4>
            <p>A very user friendly platform, with a lot of functions!</p>
          </div>
      </div>
    </div>
  </section>
</main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer containter">
  <div class="footer-links">
    <a href="https://github.com/Skalle89" target="_blank"><img class="avatar-large" src ="https://avatars.githubusercontent.com/u/47088623?v=4"></a>
    <a href="https://github.com/Antoniofqn" target="_blank"><img class="avatar-large" src="https://avatars.githubusercontent.com/u/95364917?v=4"></a>
    <a href="https://github.com/GbMattos" target="_blank"><img class="avatar-large" src ="https://avatars.githubusercontent.com/u/81327277?v=4"></a>
    <a href="https://github.com/carloseglemos" target="_blank"><img class="avatar-large" src ="https://avatars.githubusercontent.com/u/33298430?v=4"></a>
  </div>
  <div class="footer-copyright">
    <%= image_tag "https://res.cloudinary.com/dmtwwkxzz/image/upload/v1647268176/Logo-_1_akxw7e.png", class: "m-0 p-0", style: "width: 50px; height: 50px;" %>  © Copyright 2022 Dead Simple Finance
  </div>
  <div class ="footer-link-sites">
    <a href="https://www.facebook.com/Deadsimplefinance-103468955628937" target="_blank"><img class="avatar" src ="https://res.cloudinary.com/carloslemos/image/upload/v1647444845/social_facebook_fb_35_b9epiq.png"></a>
    <a href="https://www.instagram.com/deadsimplefinance/" target="_blank"><img class="avatar" src="https://res.cloudinary.com/carloslemos/image/upload/v1647444947/1491580635-yumminkysocialmedia26_83102_hprisl.png"></a>
    <a href="https://twitter.com/Deadsimplefina1" target="_blank"><img class="avatar" src ="https://res.cloudinary.com/carloslemos/image/upload/v1647445053/TWITTER_icon-icons.com_65486_lclaom.png"></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="nav">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dmtwwkxzz/image/upload/v1647268176/Logo-_1_akxw7e.png", class: "m-0 p-0", style: "width: 50px; height: 50px;" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <li class="nav-item d-flex align-items-right">
      <%= link_to calculators_path do%>
        <ion-icon size="large" name="calculator-outline" class="nav-link p-1" color="white"  ></ion-icon>
      <%end%>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item d-flex align-items-center">
          <div><ion-icon size="medium" name="home-sharp" class="nav-link p-1" color="white"></ion-icon> </div>
           <div><%= link_to "Menu", user_path(current_user), class: "nav-link p-0", style: "color:white"%></div>
          </li>
          <li class="nav-item dropdown" id="profile-picture">
            <%= navbar_avatar_has_photo?(current_user) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Transactions", user_transactions_path(current_user), class: "dropdown-item" %>
              <%= link_to "Stats", stats_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item d-flex align-items-center">
          <div><ion-icon size="large" name="log-in-outline"></ion-icon> </div>
          <div><%= link_to "Login", new_user_session_path, class:"nav-link p-0", style: "color: white;"%></div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stats/index.html.erb
<div class="container">
  <h1>Stats</h1>
  <div class="mb-4 p-2" style="border-radius: 20px; box-shadow: 10px 1px 10px 10px rgba(0,0,0,.09);">
    <h2>Last 31 days</h2>
    <%= line_chart @user.transactions.where(transactions: {category: Transaction::EXPENSE_CATEGORIES}).group(:category).group_by_day(:date).sum(:value), xmin: (Date.today - 31), xmax: Date.today, prefix: "R$ ", round: 2, zeros: true %>
  </div>
  <div class="row justify-content-around mb-4">
    <div class="col-md-5 col-12 col-lg-5 p-2" style="border-radius: 20px; box-shadow: 10px 1px 10px 10px rgba(0,0,0,.09);">
      <h2>Last Year</h2>
      <%= line_chart @user.transactions.where(transactions: {category: Transaction::EXPENSE_CATEGORIES}).group(:category).group_by_month(:date).sum(:value), xmin: (Date.today - 365), xmax: Date.today, prefix: "R$ ", round: 2, zeros: true %>
    </div>
    <div class="col-md-5 col-12 col-lg-5 p-2" style="border-radius: 20px; box-shadow: 10px 1px 10px 10px rgba(0,0,0,.09);">
      <h2>Last 12 weeks</h2>
      <%= line_chart @user.transactions.where(transactions: {category: Transaction::EXPENSE_CATEGORIES}).group(:category).group_by_week(:date).sum(:value), xmin: (Date.today - 93), xmax: Date.today, prefix: "R$ ", round: 2, zeros: true %>
    </div>
  </div>
</div>

app/views/transactions/_edit.html.erb
  <div class="modal-header">
    <h5 class="modal-title" id="editModalLabel">Change transaction</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body" data-controller="mask">
    <%= simple_form_for [current_user, transaction], remote: true  do |f| %>
      <%= f.input :date, order: [:day, :month, :year] %>
      <%= f.input :value, label: "Amount", as: :string, input_html: { data: {mask_target: "value", action:"keyup->mask#format"}, value:display_as_currency(@transaction.value), maxlength: 20} %>
      <%=
        if transaction.type_transaction == "Income"
          f.input :category, collection: Transaction::INCOME_CATEGORIES
        else
          f.input :category, collection: Transaction::EXPENSE_CATEGORIES
        end
        %>
      <%= f.input :tag %>
      <%= f.button :submit, "Change", class: "btn btn-primary", "data-action":"click->mask#send" %>
    <% end %>
  </div>

app/views/transactions/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="<%=@elem%>ModalLabel">New <%=@elem%></h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body" data-controller="mask">
  <%= render "/users/form_#{@elem}", transaction: @transaction %>
</div>

app/views/transactions/_new_expense.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="expenseModalLabel">New expense</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <%= render "/users/form_expense", transaction: @transaction %>
</div>

app/views/transactions/_transaction.html.erb
<div class="expense-card" data-user-id="<%= transaction.id %>">
  <%= content_tag(:div, transaction.date.strftime('%d/%m/%Y'))%>
  <%= content_tag(:div, transaction.category)%>
  <%= content_tag(:div,transaction.type_transaction =="Expense" ?
  display_as_currency(transaction.value * - 1) :
  display_as_currency(transaction.value)) %>
  <div class="expense-operations">
    <%= link_to "edit", edit_user_transaction_path(current_user, transaction), data: {bs_toggle:"modal", bs_target:"#editModal"}, id:"myEditModal", remote: true %>
    <%= content_tag(:div, link_to("delete", [current_user, transaction], method: :delete)) %>
  </div>
</div>

app/views/transactions/create.js.erb
<% if @transaction.errors.any? %>
  $(`#${"<%=@elem%>"}Modal .modal-content`).html('<%= j render "/transactions/new", transaction: @transaction, locals:{elem: @elem}%>');
<% else %>
  $(`#${"<%=@elem%>"}Modal`).modal('hide');
  window.location.reload()
<% end %>

app/views/transactions/edit.js.erb
$("#editModal .modal-content").html('<%= j render "/transactions/edit", transaction: @transaction %>');
$("#editModal").modal('show');

app/views/transactions/index.html.erb
<div class="row justify-content-center">
  <div class="container-expenses">
      <div class ="navbar-expenses">
        <div class="add-expense" data-controller="modal">
          New
             <%= button_tag "+",  class: "dropdown plus",
              id: "expenseDropdown", data: { bs_toggle: "dropdown" },
              'aria-haspopup': true,'aria-expanded': false
            %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="expenseDropdown">
                  <%= link_to "income", new_user_transaction_path(current_user, @transaction, elem:"income"),
                  data: {bs_toggle:"modal", bs_target:"#incomeModal", action:"click->modal#displayModal"}, remote: true, class:"dropdown-item"%>

            <%= link_to "expense", new_user_transaction_path(current_user, @transaction,  elem: "expense"),
              data: {bs_toggle:"modal", bs_target:"#expenseModal", action:"click->modal#displayModal"}, remote: true, class:"dropdown-item"%>
            </div>

            <div class="modal fade my_target" id="incomeModal" tabindex="-1" aria-labelledby="incomeModalLabel" aria-hidden="true" data-modal-target="incomeModal">
              <div class="modal-dialog">
                  <div class="modal-content">
                  </div>
                </div>
            </div>

            <div class="modal fade my_target" id="expenseModal"  aria-labelledby="expenseModalLabel" tabindex="-1" aria-hidden="true" data-modal-target="expenseModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                    </div>
                </div>
            </div>
        </div>
        <div class="time-selection">
        </div>
      </div>
      <div class="table-expenses">
          <div>Filter by...</div>
          <div class = "income-expense">
            <%= button_to "income", user_transactions_path, method: :get, params: {query: "Income"} %>
            <%= button_to "expenses", user_transactions_path, method: :get, params: {query: "Expense"} %>
            <%= button_to "all", user_transactions_path, method: :get, params: {query: "all"} %>
          </div>
      </div>

       <%= render @transactions.sort_by(&:date)%>

       <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content">
              </div>
          </div>
        </div>

      <div class="footer-expenses">
        <div>My balance</div>
        <div>
          <%= extract_values(@transactions) %>
        </div>
      </div>
    </div>
  </div>
</div>